### ISSUE TITLE
History is still being stored by your WEBVIEW2 environment  -> (Your Package)\LocalState\EBWebView\Default\HIstory

### ISSUE THREAD

**Issue by JohnDizzle** [FirebrowserDevs/FireBrowser-Uwp#3]
I really enjoy your application, and all the features that your team has done.   It's really nice and sleek.   
I was wondering if you guys know about all of the files that are in your \default  folder .   
IT seems to store all sort of information in these different database files... 

I was able to get some information from a MSFT guy here.
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3009#issuecomment-1332515849

Although the windowsappk 1.4.231008000 doesn't have an option to create an ENVIRONMENT... 
but I am able to delete the history that is stored in these files.

**Comment by jarno9981** [comment]
> I really enjoy your application, and all the features that your team has done.   It's really nice and sleek.   
> I was wondering if you guys know about all of the files that are in your \default  folder .   
> IT seems to store all sort of information in these different database files... 
> 
> I was able to get some information from a MSFT guy here.
> https://github.com/MicrosoftEdge/WebView2Feedback/issues/3009#issuecomment-1332515849
> 
> Although the windowsappk 1.4.231008000 doesn't have an option to create an ENVIRONMENT... 
> but I am able to delete the history that is stored in these files. 
> 

Yeah we know of the \default folder we always used the history db in there but after some issues with that it now uses costum db but we are working on full winui3 version of the app and in te future will try to bypass that folder

**Comment by jarno9981** [comment]
> > I really enjoy your application, and all the features that your team has done.   It's really nice and sleek.   
> > I was wondering if you guys know about all of the files that are in your \default  folder .   
> > IT seems to store all sort of information in these different database files... 
> > 
> > I was able to get some information from a MSFT guy here.
> > https://github.com/MicrosoftEdge/WebView2Feedback/issues/3009#issuecomment-1332515849
> > 
> > Although the windowsappk 1.4.231008000 doesn't have an option to create an ENVIRONMENT... 
> > but I am able to delete the history that is stored in these files. 
> > 
> 
> Yeah we know of the \default folder we always used the history db in there but after some issues with that it now uses costum db but we are working on full winui3 version of the app and in te future will try to bypass that folder 

The winui3 app is currently using the envoriment options to set to costum path {username}\browser

Its i  private now but testing is available on our discord https://discord.gg/kYStRKBHwy
